const CITIES_WEATHER = [
  {
    id: "city001",
    city: "تهران",
    city_en: "Tehran",
    country: "ایران",
    temperature: {
      current: 22, // سلسیوس
      history: [
        { hour: "10:00", temp: 20 },
        { hour: "11:00", temp: 21 },
        { hour: "12:00", temp: 23 },
        { hour: "13:00", temp: 24 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 25 },
        { date: "FRIDAY", temp: 23 },
        { date: "THURSDAY", temp: 21 },
      ],
    },
    status: "آفتابی", // وضعیت فعلی آب و هوا
  },
  {
    id: "city002",
    city: "لندن",
    city_en: "London",
    country: "بریتانیا",
    temperature: {
      current: 15,
      history: [
        { hour: "08:00", temp: 13 },
        { hour: "09:00", temp: 14 },
        { hour: "10:00", temp: 16 },
        { hour: "11:00", temp: 17 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 18 },
        { date: "FRIDAY", temp: 16 },
        { date: "THURSDAY", temp: 14 },
      ],
    },
    status: "ابری",
  },
  {
    id: "city003",
    city: "توکیو",
    city_en: "Tokyo",
    country: "ژاپن",
    temperature: {
      current: 28,
      history: [
        { hour: "13:00", temp: 26 },
        { hour: "14:00", temp: 27 },
        { hour: "15:00", temp: 29 },
        { hour: "16:00", temp: 30 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 31 },
        { date: "FRIDAY", temp: 29 },
        { date: "THURSDAY", temp: 27 },
      ],
    },
    status: "گرم و شرجی",
  },
  {
    id: "city004",
    city: "نیویورک",
    city_en: "New York",
    country: "ایالات متحده",
    temperature: {
      current: 18,
      history: [
        { hour: "09:00", temp: 17 },
        { hour: "10:00", temp: 18 },
        { hour: "11:00", temp: 19 },
        { hour: "12:00", temp: 20 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 21 },
        { date: "FRIDAY", temp: 19 },
        { date: "THURSDAY", temp: 17 },
      ],
    },
    status: "باد و کمی ابری",
  },
  {
    id: "city005",
    city: "سیدنی",
    city_en: "Sydney",
    country: "استرالیا",
    temperature: {
      current: 25,
      history: [
        { hour: "11:00", temp: 23 },
        { hour: "12:00", temp: 24 },
        { hour: "13:00", temp: 26 },
        { hour: "14:00", temp: 27 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 28 },
        { date: "FRIDAY", temp: 26 },
        { date: "THURSDAY", temp: 24 },
      ],
    },
    status: "صاف و آفتابی",
  },
  {
    id: "city006",
    city: "برلین",
    city_en: "Berlin",
    country: "آلمان",
    temperature: {
      current: 12,
      history: [
        { hour: "10:00", temp: 11 },
        { hour: "11:00", temp: 12 },
        { hour: "12:00", temp: 13 },
        { hour: "13:00", temp: 14 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 15 },
        { date: "FRIDAY", temp: 13 },
        { date: "THURSDAY", temp: 11 },
      ],
    },
    status: "بارانی",
  },
  {
    id: "city007",
    city: "ریو دو ژانیرو",
    city_en: "Rio de Janeiro",
    country: "برزیل",
    temperature: {
      current: 30,
      history: [
        { hour: "13:00", temp: 29 },
        { hour: "14:00", temp: 30 },
        { hour: "15:00", temp: 31 },
        { hour: "16:00", temp: 32 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 33 },
        { date: "FRIDAY", temp: 31 },
        { date: "THURSDAY", temp: 29 },
      ],
    },
    status: "گرم و مرطوب",
  },
  {
    id: "city008",
    city: "مسکو",
    city_en: "Moscow",
    country: "روسیه",
    temperature: {
      current: 8,
      history: [
        { hour: "11:00", temp: 7 },
        { hour: "12:00", temp: 8 },
        { hour: "13:00", temp: 9 },
        { hour: "14:00", temp: 10 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 11 },
        { date: "FRIDAY", temp: 9 },
        { date: "THURSDAY", temp: 7 },
      ],
    },
    status: "نیمه ابری",
  },
  {
    id: "city009",
    city: "پکن",
    city_en: "Beijing",
    country: "چین",
    temperature: {
      current: 25,
      history: [
        { hour: "12:00", temp: 24 },
        { hour: "13:00", temp: 25 },
        { hour: "14:00", temp: 26 },
        { hour: "15:00", temp: 27 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 28 },
        { date: "FRIDAY", temp: 26 },
        { date: "THURSDAY", temp: 24 },
      ],
    },
    status: "کمی ابری",
  },
  {
    id: "city010",
    city: "پاریس",
    city_en: "Paris",
    country: "فرانسه",
    temperature: {
      current: 17,
      history: [
        { hour: "11:00", temp: 16 },
        { hour: "12:00", temp: 17 },
        { hour: "13:00", temp: 18 },
        { hour: "14:00", temp: 19 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 20 },
        { date: "FRIDAY", temp: 18 },
        { date: "THURSDAY", temp: 16 },
      ],
    },
    status: "ابری",
  },
  {
    id: "city011",
    city: "رم",
    city_en: "Rome",
    country: "ایتالیا",
    temperature: {
      current: 23,
      history: [
        { hour: "12:00", temp: 22 },
        { hour: "13:00", temp: 23 },
        { hour: "14:00", temp: 24 },
        { hour: "15:00", temp: 25 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 26 },
        { date: "FRIDAY", temp: 24 },
        { date: "THURSDAY", temp: 22 },
      ],
    },
    status: "آفتابی",
  },
  {
    id: "city012",
    city: "قاهره",
    city_en: "Cairo",
    country: "مصر",
    temperature: {
      current: 32,
      history: [
        { hour: "13:00", temp: 31 },
        { hour: "14:00", temp: 32 },
        { hour: "15:00", temp: 33 },
        { hour: "16:00", temp: 34 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 35 },
        { date: "FRIDAY", temp: 33 },
        { date: "THURSDAY", temp: 31 },
      ],
    },
    status: "گرم و خشک",
  },
  {
    id: "city013",
    city: "استانبول",
    city_en: "Istanbul",
    country: "ترکیه",
    temperature: {
      current: 20,
      history: [
        { hour: "12:00", temp: 19 },
        { hour: "13:00", temp: 20 },
        { hour: "14:00", temp: 21 },
        { hour: "15:00", temp: 22 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 23 },
        { date: "FRIDAY", temp: 21 },
        { date: "THURSDAY", temp: 19 },
      ],
    },
    status: "صاف",
  },
  {
    id: "city014",
    city: "مکزیکو سیتی",
    city_en: "Mexico City",
    country: "مکزیک",
    temperature: {
      current: 21,
      history: [
        { hour: "11:00", temp: 20 },
        { hour: "12:00", temp: 21 },
        { hour: "13:00", temp: 22 },
        { hour: "14:00", temp: 23 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 24 },
        { date: "FRIDAY", temp: 22 },
        { date: "THURSDAY", temp: 20 },
      ],
    },
    status: "باد و کمی ابری",
  },
  {
    id: "city015",
    city: "سئول",
    city_en: "Seoul",
    country: "کره جنوبی",
    temperature: {
      current: 26,
      history: [
        { hour: "13:00", temp: 25 },
        { hour: "14:00", temp: 26 },
        { hour: "15:00", temp: 27 },
        { hour: "16:00", temp: 28 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 29 },
        { date: "FRIDAY", temp: 27 },
        { date: "THURSDAY", temp: 25 },
      ],
    },
    status: "گرم و شرجی",
  },
  {
    id: "city016",
    city: "شانگهای",
    city_en: "Shanghai",
    country: "چین",
    temperature: {
      current: 29,
      history: [
        { hour: "13:00", temp: 28 },
        { hour: "14:00", temp: 29 },
        { hour: "15:00", temp: 30 },
        { hour: "16:00", temp: 31 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 32 },
        { date: "FRIDAY", temp: 30 },
        { date: "THURSDAY", temp: 28 },
      ],
    },
    status: "گرم و مرطوب",
  },
  {
    id: "city017",
    city: "بوئنوس آیرس",
    city_en: "Buenos Aires",
    country: "آرژانتین",
    temperature: {
      current: 22,
      history: [
        { hour: "11:00", temp: 21 },
        { hour: "12:00", temp: 22 },
        { hour: "13:00", temp: 23 },
        { hour: "14:00", temp: 24 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 25 },
        { date: "FRIDAY", temp: 23 },
        { date: "THURSDAY", temp: 21 },
      ],
    },
    status: "صاف",
  },
  {
    id: "city018",
    city: "دهلی",
    city_en: "Delhi",
    country: "هند",
    temperature: {
      current: 30,
      history: [
        { hour: "13:00", temp: 29 },
        { hour: "14:00", temp: 30 },
        { hour: "15:00", temp: 31 },
        { hour: "16:00", temp: 32 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 33 },
        { date: "FRIDAY", temp: 31 },
        { date: "THURSDAY", temp: 29 },
      ],
    },
    status: "گرم و آفتابی",
  },
  {
    id: "city019",
    city: "سنگاپور",
    city_en: "Singapore",
    country: "سنگاپور",
    temperature: {
      current: 31,
      history: [
        { hour: "13:00", temp: 30 },
        { hour: "14:00", temp: 31 },
        { hour: "15:00", temp: 32 },
        { hour: "16:00", temp: 33 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 33 },
        { date: "FRIDAY", temp: 32 },
        { date: "THURSDAY", temp: 30 },
      ],
    },
    status: "گرم و مرطوب",
  },
  {
    id: "city020",
    city: "شیکاگو",
    city_en: "Chicago",
    country: "ایالات متحده",
    temperature: {
      current: 16,
      history: [
        { hour: "10:00", temp: 15 },
        { hour: "11:00", temp: 16 },
        { hour: "12:00", temp: 17 },
        { hour: "13:00", temp: 18 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 19 },
        { date: "FRIDAY", temp: 17 },
        { date: "THURSDAY", temp: 15 },
      ],
    },
    status: "باد و کمی ابری",
  },
  {
    id: "city021",
    city: "جاکارتا",
    city_en: "Jakarta",
    country: "اندونزی",
    temperature: {
      current: 30,
      history: [
        { hour: "13:00", temp: 29 },
        { hour: "14:00", temp: 30 },
        { hour: "15:00", temp: 31 },
        { hour: "16:00", temp: 32 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 32 },
        { date: "FRIDAY", temp: 31 },
        { date: "THURSDAY", temp: 29 },
      ],
    },
    status: "گرم و مرطوب",
  },
  {
    id: "city022",
    city: "منچستر",
    city_en: "Manchester",
    country: "بریتانیا",
    temperature: {
      current: 14,
      history: [
        { hour: "10:00", temp: 13 },
        { hour: "11:00", temp: 14 },
        { hour: "12:00", temp: 15 },
        { hour: "13:00", temp: 16 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 17 },
        { date: "FRIDAY", temp: 15 },
        { date: "THURSDAY", temp: 13 },
      ],
    },
    status: "بارانی",
  },
  {
    id: "city023",
    city: "آمستردام",
    city_en: "Amsterdam",
    country: "هلند",
    temperature: {
      current: 13,
      history: [
        { hour: "10:00", temp: 12 },
        { hour: "11:00", temp: 13 },
        { hour: "12:00", temp: 14 },
        { hour: "13:00", temp: 15 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 16 },
        { date: "FRIDAY", temp: 14 },
        { date: "THURSDAY", temp: 12 },
      ],
    },
    status: "ابری",
  },
  {
    id: "city024",
    city: "استکهلم",
    city_en: "Stockholm",
    country: "سوئد",
    temperature: {
      current: 10,
      history: [
        { hour: "10:00", temp: 9 },
        { hour: "11:00", temp: 10 },
        { hour: "12:00", temp: 11 },
        { hour: "13:00", temp: 12 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 13 },
        { date: "FRIDAY", temp: 11 },
        { date: "THURSDAY", temp: 9 },
      ],
    },
    status: "باد و کمی ابری",
  },
  {
    id: "city025",
    city: "اسلو",
    city_en: "Oslo",
    country: "نروژ",
    temperature: {
      current: 9,
      history: [
        { hour: "10:00", temp: 8 },
        { hour: "11:00", temp: 9 },
        { hour: "12:00", temp: 10 },
        { hour: "13:00", temp: 11 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 12 },
        { date: "FRIDAY", temp: 10 },
        { date: "THURSDAY", temp: 8 },
      ],
    },
    status: "نیمه ابری",
  },
  {
    id: "city026",
    city: "هلسینکی",
    city_en: "Helsinki",
    country: "فنلاند",
    temperature: {
      current: 11,
      history: [
        { hour: "10:00", temp: 10 },
        { hour: "11:00", temp: 11 },
        { hour: "12:00", temp: 12 },
        { hour: "13:00", temp: 13 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 14 },
        { date: "FRIDAY", temp: 12 },
        { date: "THURSDAY", temp: 10 },
      ],
    },
    status: "ابری",
  },
  {
    id: "city027",
    city: "کپنهاگ",
    city_en: "Copenhagen",
    country: "دانمارک",
    temperature: {
      current: 12,
      history: [
        { hour: "10:00", temp: 11 },
        { hour: "11:00", temp: 12 },
        { hour: "12:00", temp: 13 },
        { hour: "13:00", temp: 14 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 15 },
        { date: "FRIDAY", temp: 13 },
        { date: "THURSDAY", temp: 11 },
      ],
    },
    status: "صاف",
  },
  {
    id: "city028",
    city: "وین",
    city_en: "Vienna",
    country: "اتریش",
    temperature: {
      current: 16,
      history: [
        { hour: "11:00", temp: 15 },
        { hour: "12:00", temp: 16 },
        { hour: "13:00", temp: 17 },
        { hour: "14:00", temp: 18 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 19 },
        { date: "FRIDAY", temp: 17 },
        { date: "THURSDAY", temp: 15 },
      ],
    },
    status: "کمی ابری",
  },
  {
    id: "city029",
    city: "زوریخ",
    city_en: "Zurich",
    country: "سوئیس",
    temperature: {
      current: 18,
      history: [
        { hour: "11:00", temp: 17 },
        { hour: "12:00", temp: 18 },
        { hour: "13:00", temp: 19 },
        { hour: "14:00", temp: 20 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 21 },
        { date: "FRIDAY", temp: 19 },
        { date: "THURSDAY", temp: 17 },
      ],
    },
    status: "آفتابی",
  },
  {
    id: "city030",
    city: "بروکسل",
    city_en: "Brussels",
    country: "بلژیک",
    temperature: {
      current: 14,
      history: [
        { hour: "10:00", temp: 13 },
        { hour: "11:00", temp: 14 },
        { hour: "12:00", temp: 15 },
        { hour: "13:00", temp: 16 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 17 },
        { date: "FRIDAY", temp: 15 },
        { date: "THURSDAY", temp: 13 },
      ],
    },
    status: "ابری",
  },
  {
    id: "city031",
    city: "لیسبون",
    city_en: "Lisbon",
    country: "پرتغال",
    temperature: {
      current: 20,
      history: [
        { hour: "12:00", temp: 19 },
        { hour: "13:00", temp: 20 },
        { hour: "14:00", temp: 21 },
        { hour: "15:00", temp: 22 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 23 },
        { date: "FRIDAY", temp: 21 },
        { date: "THURSDAY", temp: 19 },
      ],
    },
    status: "صاف و آفتابی",
  },
  {
    id: "city032",
    city: "آتن",
    city_en: "Athens",
    country: "یونان",
    temperature: {
      current: 26,
      history: [
        { hour: "13:00", temp: 25 },
        { hour: "14:00", temp: 26 },
        { hour: "15:00", temp: 27 },
        { hour: "16:00", temp: 28 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 29 },
        { date: "FRIDAY", temp: 27 },
        { date: "THURSDAY", temp: 25 },
      ],
    },
    status: "گرم و آفتابی",
  },
  {
    id: "city033",
    city: "هنگ کنگ",
    city_en: "Hong Kong",
    country: "چین",
    temperature: {
      current: 29,
      history: [
        { hour: "13:00", temp: 28 },
        { hour: "14:00", temp: 29 },
        { hour: "15:00", temp: 30 },
        { hour: "16:00", temp: 31 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 32 },
        { date: "FRIDAY", temp: 30 },
        { date: "THURSDAY", temp: 28 },
      ],
    },
    status: "گرم و مرطوب",
  },
  {
    id: "city034",
    city: "بانکوک",
    city_en: "Bangkok",
    country: "تایلند",
    temperature: {
      current: 31,
      history: [
        { hour: "13:00", temp: 30 },
        { hour: "14:00", temp: 31 },
        { hour: "15:00", temp: 32 },
        { hour: "16:00", temp: 33 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 33 },
        { date: "FRIDAY", temp: 32 },
        { date: "THURSDAY", temp: 30 },
      ],
    },
    status: "گرم و شرجی",
  },
  {
    id: "city035",
    city: "دبی",
    city_en: "Dubai",
    country: "امارات متحده عربی",
    temperature: {
      current: 35,
      history: [
        { hour: "13:00", temp: 34 },
        { hour: "14:00", temp: 35 },
        { hour: "15:00", temp: 36 },
        { hour: "16:00", temp: 37 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 38 },
        { date: "FRIDAY", temp: 36 },
        { date: "THURSDAY", temp: 34 },
      ],
    },
    status: "گرم و آفتابی",
  },
  {
    id: "city036",
    city: "ریاض",
    city_en: "Riyadh",
    country: "عربستان سعودی",
    temperature: {
      current: 38,
      history: [
        { hour: "13:00", temp: 37 },
        { hour: "14:00", temp: 38 },
        { hour: "15:00", temp: 39 },
        { hour: "16:00", temp: 40 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 41 },
        { date: "FRIDAY", temp: 39 },
        { date: "THURSDAY", temp: 37 },
      ],
    },
    status: "گرم و خشک",
  },
  {
    id: "city037",
    city: "دوحه",
    city_en: "Doha",
    country: "قطر",
    temperature: {
      current: 36,
      history: [
        { hour: "13:00", temp: 35 },
        { hour: "14:00", temp: 36 },
        { hour: "15:00", temp: 37 },
        { hour: "16:00", temp: 38 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 39 },
        { date: "FRIDAY", temp: 37 },
        { date: "THURSDAY", temp: 35 },
      ],
    },
    status: "گرم و مرطوب",
  },
  {
    id: "city038",
    city: "کوالالامپور",
    city_en: "Kuala Lumpur",
    country: "مالزی",
    temperature: {
      current: 30,
      history: [
        { hour: "13:00", temp: 29 },
        { hour: "14:00", temp: 30 },
        { hour: "15:00", temp: 31 },
        { hour: "16:00", temp: 32 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 32 },
        { date: "FRIDAY", temp: 31 },
        { date: "THURSDAY", temp: 29 },
      ],
    },
    status: "گرم و شرجی",
  },
  {
    id: "city039",
    city: "جوهانسبرگ",
    city_en: "Johannesburg",
    country: "آفریقای جنوبی",
    temperature: {
      current: 20,
      history: [
        { hour: "11:00", temp: 19 },
        { hour: "12:00", temp: 20 },
        { hour: "13:00", temp: 21 },
        { hour: "14:00", temp: 22 },
      ],
      pastDays: [
        { date: "SATURDAY", temp: 23 },
        { date: "FRIDAY", temp: 21 },
        { date: "FRIDAY", temp: 21 },
      ],
    },
  },
];

export default CITIES_WEATHER;
